### ISSUE TITLE
Wistia video in news section

### ISSUE THREAD

**Issue by seanwilcox** [HawkRidgeSystems/HRS-Main#10]
Kim wanted me to put up a new post in news about 3D Systems, and there is a video to go with it.

I have added the video, and put the custom script in, but when clicked the video still plays in the full window frame.

http://www.hawkridgesys.com/news/post/3d-systems-announces-availability-of-3dme-photobooth-at-euromold-2014/

**Comment by jhonparedes** [comment]
Fixed with 
https://github.com/HawkRidgeSystems/HRS-Main/commit/ec64cddb31e6f29214be31b7dfb07f6b3c8ac145
