### ISSUE TITLE
Add Headers to Blog Sections in Product Pages

### ISSUE THREAD

**Issue by seanwilcox** [HawkRidgeSystems/HRS-Main#14]
For Simulation, EPDM, Composer, Electrical, and CAMWorks – add (Product Name) Blog as a header, per Kimberly's request. Thank you.

**Comment by jhonparedes** [comment]
Add the following to scripts add blog headers 

    $( "<h2 class='page-header'><a href='/blog/category/camworks/'>CAMWorks Blog</a></h2>" ).prependTo( ".topsection" );
