### ISSUE TITLE
Video category alignment off

### ISSUE THREAD

**Issue by seanwilcox** [HawkRidgeSystems/HRS-Main#19]
For the related videos section under a video, there is a bunch of blank space in row that breaks up the categories (seen here): http://www.hawkridgesys.com/products/solidworks/videos/chain-component-pattern/

**Comment by jhonparedes** [comment]
Probably a clear issue. 

![screen shot 2014-12-31 at 4 06 22 pm](https://cloud.githubusercontent.com/assets/5641734/5591282/ff1bdb7c-9106-11e4-9efc-610453f9b30d.png)
